### ISSUE TITLE
upgrade to polar 1.2

### ISSUE THREAD

**Issue by ywangwxd** [reczoo/FuxiCTR#100]
when upgrade to polar 1.2, some functions used are deprecated. For example.
in criteo.py
 # return pl.col(col_name).apply(_convert_to_bucket).cast(pl.Int32)
        return pl.col(col_name).map_elements(_convert_to_bucket, return_dtype=pl.Int32)

the function "apply” is not used anymore.

**Comment by zhujiem** [comment]
Please follow the environment settings: https://github.com/reczoo/FuxiCTR/discussions/99
