### ISSUE TITLE
Maybe a bug found in feature_preprocess.py #103

### ISSUE THREAD

**Issue by ywangwxd** [reczoo/FuxiCTR#105]
In your case, the configuration should be:
```
preprocess: convert_to_bucket(col_name)
```

_Originally posted by @zhujiem in https://github.com/reczoo/FuxiCTR/issues/103#issuecomment-2247839849_

**Comment by ywangwxd** [comment]
Sorry for filing a new issue, you have closed the old one but I have not verified your solution yet.

The way you suggested here caused another error. Maybe I misunderstood you.
If I set the configure are exactly as you said, the code will not understand "col_name", unless line 18 in my original issue parse this argument as the variable "name", this means code change. Or, if you mean put a column name string like 
preprocess: convert_to_bucket("I2")
Then this means you need to specify it for each column separately, which is unlikely what you mean.

**Comment by zhujiem** [comment]
Yes. It is designed to follow the latter case -- specify it for each column separately.

**Comment by ywangwxd** [comment]
> Yes. It is designed to follow the latter case -- specify it for each column separately.

Then I strongly suggest change the code as what I did in the first issue. It is simple, just always give the column name as the default argument, the usde-defined proprocessor can use it or not. Indeed most likely it is needed because it is processing a
specific column. Setting the column name as the argument in the configure for EACH column is not desirable. It also makes the configure file complicated but meaningless, e.g., too many duplicate texts.

**Comment by zhujiem** [comment]
Thanks for your suggestion. Directly plugging the col_name in the user_defined_processor will lead to issues in functions such as "copy_from(src_col_name)". So, I remove it in the current version. I will improve it in the next version. Thanks!
