### ISSUE TITLE
how to append prediction result to original dataset. 

### ISSUE THREAD

**Issue by quency711** [reczoo/FuxiCTR#114]
你好，我想请问一下我用完model predict出了结果之后，如何讲这个结果加回到原来的data当中。
比如说我的dataset里有user_id和offer_id，我希望得到结果之后能把rank score 加回到原有的dataset中，这样我可以根据user_id和offer_id得到它对应的rank score. 

感谢

**Comment by zhujiem** [comment]
如果是在训练阶段，没法直接加到dataset中，因为数据会shuffle。在train_step()中有一个return_dict，需要添加你说的user_id, offer_id，和score，然后把这三个字段进行append，最后保存一个单独的文件。https://github.com/reczoo/FuxiCTR/blob/main/fuxictr/pytorch/models/rank_model.py#L192

如果测试阶段，对应predict函数https://github.com/reczoo/FuxiCTR/blob/main/fuxictr/pytorch/models/rank_model.py#L246 中中的return_dict
