### ISSUE TITLE
多任务执行有BUG

### ISSUE THREAD

**Issue by ChengQianlong** [reczoo/FuxiCTR#115]
执行 model_zoo/multitask/MMoE/run_expid.py 会报错“TypeError: unhashable type: 'slice'”
初步看了下应该是 fuxictr/pytorch/models/multitask_model.py 里面的 78行 
y = [inputs[:, self.feature_map.get_column_index(labels[i])].to(self.device).float().view(-1, 1)
             for i in range(len(labels))]

inputs是一个字典，不能进行切片操作。

**Comment by zhujiem** [comment]
麻烦试一下老版本：https://github.com/reczoo/FuxiCTR/tree/b885db9fc95fa34743786aee2b2febc1c398d53f/model_zoo/multitask

可能新版本导致了问题，需要修复。

**Comment by zhujiem** [comment]
Bug已修复，可以再试一下。
