### ISSUE TITLE
About Sequence Data

### ISSUE THREAD

**Issue by Jary-lrj** [reczoo/FuxiCTR#116]
in data/tiny_csv:
There is a problem with the sample sequence data. Why does a click sequence exist at one specific moment? What does this mean?
As far as I understand, there shouldn't be a click sequence at one moment. If there is, which adgroup does clk represent that was clicked?
If click_sequence represents the click sequence before this moment, then there is a problem of data redundancy. I don't quite understand this and hope to get your answer.

**Comment by zhujiem** [comment]
Yes, click_sequence denotes the clicked item sequence before the time of this sample. In online environement, this sequence feature is updated realtime.
