### ISSUE TITLE
[Bug] add_loss() is not working after renaming to compute_loss() in BaseModel

### ISSUE THREAD

**Issue by Sharan123** [reczoo/FuxiCTR#122]
Hello! 

I've noticed that the `fuxictr/pytorch/rank_model.py`, specifically `BaseModel` class uses the `compute_loss` method in its `train_step` and then for the backprop. However, I've also noticed that the newest DCNv3 (ECN and DCNv3) along with the DIEN, DMIN, DMR and FinalNet all have implemented add_loss instead of compute_loss. Example from DCNv3

```python
def add_loss(self, inputs):
        return_dict = self.forward(inputs)
        y_true = self.get_labels(inputs)
        weight = torch.where(y_true==1., self.pos_weight, 1)
        y_pred = return_dict["y_pred"]
        y_d = return_dict["y_d"]
        y_s = return_dict["y_s"]
        loss = self.loss_fn(y_pred, y_true, reduction='mean', weight=weight)
        loss_d = self.loss_fn(y_d, y_true, reduction='mean', weight=weight)
        loss_s = self.loss_fn(y_s, y_true, reduction='mean', weight=weight)
        weight_d = loss_d - loss
        weight_s = loss_s - loss
        weight_d = torch.where(weight_d > 0, weight_d, torch.zeros(1).to(weight_d.device))
        weight_s = torch.where(weight_s > 0, weight_s, torch.zeros(1).to(weight_s.device))
        loss = loss + loss_d * weight_d + loss_s * weight_s
        return loss
```
With no compute_loss implemented

`add_loss` does appear in the tensorflow model version - `fuxictr/tensorflow/rank_model.py` but NOT in the pytorch version of `fuxictr/pytorch/rank_model.py` 
In the README it says that all of these methods are implemented in pytorch and the mentioned models clearly use pytorch version of the `BaseModel`.  The question is (and I do apologize if these appear basic, I did try searching for the answers): 

- Where is `add_loss` invoked or called? I cannot find that this is a standard part of `nn.Module` and it is not called in the `BaseModel`. Searching for `add_loss` only gives the tensorflow rank_model.py version
- How are `add_loss` and `compute_loss` connected, can we swap the `add_loss` with the `compute_loss`? 

The reason for this question is that I am developing a python mixin class that would enable all models to utilize ranking with just inheriting the mixin and relying on the mixin's compute_loss method. And I did notice that if compute_loss is the default - it stays compute_loss, but if we have additional factors, the model class usually usually uses add_loss instead. So I am curious how I can utilize this add_loss into the ranking mixin model as well as figuring out how this add_loss is being invoked.

UPDATE: Adding a print statement in the add_loss of DCNv3 and calling the model did not yield in the print statement being shown (likely meaning that we are never invoking the add_loss?) Is this a bug as the intended method compute_loss in this case?

**Comment by zhujiem** [comment]
Thanks for raising the issue. I found this is a bug caused by rename from "add_loss" to "compute_loss". 
"add_loss" works for FuxiCTR<=2.0.2.
https://github.com/reczoo/FuxiCTR/blob/v2.0.2/fuxictr/pytorch/models/ctr_model.py#L66
I will fix it soon.
