### ISSUE TITLE
在taobaoad上跑DIEN_amazonelectronics_x1_022_a22ee885，内存溢出

### ISSUE THREAD

**Issue by sangzige** [reczoo/FuxiCTR#124]
内存32g，显卡3060，运行时出现报错。后把batch size调整为128，ParquetBlockDataLoader的buffer size设置到1000，还是不行。最后在spawn.py中运行到126行self = reduction.pickle.load(from_parent)提示memoryError。debug跟踪下去，大致是在dataloader.py的414-415行出现问题，            self.check_worker_number_rationality()
            return _MultiProcessingDataLoaderIter(self)，在return时最终进入了spawn.py。

![e452058a-71fe-4b71-8275-35e3d6f5f1f3](https://github.com/user-attachments/assets/125309be-c1a2-411a-b9d1-03bdb0a35c11)

**Comment by sangzige** [comment]
<img width="590" alt="56200576d9f011672842acdff297246" src="https://github.com/user-attachments/assets/277f5b15-a50e-4feb-944d-6b365acd79f6">
<img width="849" alt="f7f4c14fc2786abc09bd1c1aedf4794" src="https://github.com/user-attachments/assets/9a67b626-86b2-499f-a0e4-a25458c3cade">
在对batch_iterator遍历时出错

**Comment by zhujiem** [comment]
This issue can be fixed by setting "data_block_size: 100000" to split the dataset into smaller parts. Please refer to https://github.com/reczoo/RecSys2024_CTR_Challenge/blob/main/config/DIN_ebnerd_large_x1_tuner_config_01.yaml#L13C9-L13C32 for an example.

**Comment by sangzige** [comment]
@zhujiem 一开始batch size调整到8，也可以跑，但是一个epoch结束以后，就报错了。后面采用你提到的方法，she设置block size大小，但是第一个epoch结束后，在验证集上又出现memory error
![image](https://github.com/user-attachments/assets/cfb8d771-f07f-4367-bdfe-b79aa836fc34)
![image](https://github.com/user-attachments/assets/b02f313e-0705-4b29-aad2-cea57d58dc15)

![image](https://github.com/user-attachments/assets/8a495cb9-2ae0-4891-82df-0bc180201f45)

**Comment by sangzige** [comment]
而且训练过程中，cpu跟gpu占用几乎不变
<img width="429" alt="4ee3de595750fb1e44bc80c525dd711" src="https://github.com/user-attachments/assets/5b3260cf-0ad1-4a11-ad89-084fc9253cb5">
