### ISSUE TITLE
[Bug] apply was renamed to .map_elements()

### ISSUE THREAD

**Issue by byby221b** [reczoo/FuxiCTR#127]
"In Polars, the apply method has been renamed to .map_elements(). Therefore, the .apply() method on line 95 of feature_processor.py needs to be updated. Otherwise, an AttributeError: 'Expr' object has no attribute 'apply' will occur."

Reference: https://stackoverflow.com/questions/78753820/using-polars-with-python-and-being-thrown-the-following-exception-attributeerro

**Comment by zhujiem** [comment]
which version of polars do you use?

**Comment by zhujiem** [comment]
To backward support python 3.6, 3.7, 3.8, we currently only support polars <= 1.0.0.
