### ISSUE TITLE
Why ETA, SDIM are only implemented in the `dev` branch

### ISSUE THREAD

**Issue by byby221b** [reczoo/FuxiCTR#133]
Hello! I noticed that some model structures (e.g., **ETA, SDIM**) have been implemented in the `dev` branch but haven’t been merged into the `master` branch. Are these models stable and ready for use, or are there known issues? 

Additionally, are there any plans to implement ultra-long sequence models like **SIM** or **TWIN** in the future? 

Thank you so much!

**Comment by zhujiem** [comment]
Both models are put in https://github.com/reczoo/FuxiCTR/tree/main/model_zoo/LongCTR

Yes, we are interested in SIM and TWIN. But it's not ready yet.

**Comment by byby221b** [comment]
Get it~ Thanks 👍
