### ISSUE TITLE
关于自己写的一个简单的新模型

### ISSUE THREAD

**Issue by ySh-eng** [reczoo/FuxiCTR#90]
我自己设计了一个非常简单的模型，非常简单（类似于MaskedNet），运行速度很快。因为现在毕业了没有GPU资源，所以几乎没有经过调参，但是准确率仅次于FinalMLP，请问下你们有兴趣接手一下吗？

**Comment by zhujiem** [comment]
请问你的模型优化目的是什么？

**Comment by ySh-eng** [comment]
是为了发论文

**Comment by zhujiem** [comment]
那可以有对应后提交PR我们收录一下~

**Comment by ySh-eng** [comment]
抱歉，我没太看懂您的意思。请问下有对应是什么意思呢，提交PR又是什么呢？

**Comment by zhujiem** [comment]
写漏了，再看下。

**Comment by zhujiem** [comment]
你想要贡献一些代码：https://github.com/reczoo/FuxiCTR/issues/89

**Comment by ySh-eng** [comment]
我现在只有代码，没有论文。现在毕业了没人指导，我也是第一次写论文，会有点困难，也不知道该投稿哪里。另外现在没有GPU，也没办法调参。所以我想请问下你们有兴趣接手这个代码吗？

**Comment by zhujiem** [comment]
那你没有证明它的价值啊，论文、比赛、或者上线效果？

**Comment by ySh-eng** [comment]
好的，我知道了。麻烦您啦！
