### ISSUE TITLE
生成的数据格式疑问？

### ISSUE THREAD

**Issue by xuened** [reczoo/FuxiCTR#91]
example1_build_dataset_to_npz.py运行完之后，生成的数据test train valid都没有尾缀.npz呀，后面读取文件的时候就会报错例如不存在train.npz
另外强制加了npz尾缀之后，读取又显示ValueError: Cannot load file containing pickled data when allow_pickle=False
感谢解答！

**Comment by zhujiem** [comment]
https://github.com/reczoo/FuxiCTR/tree/v2.2.3

**Comment by zhujiem** [comment]
麻烦npz格式先使用v2.2.3版本，当前版本可能确实还没适配好。

**Comment by xuened** [comment]
***@***.***
大佬请问我想加点其他评价指标这么操作合适不，咱们这个做CTR，0/1分类，我想拿来做多分类，看这里面评价指标没有多分类的。
十分感谢回复！

发件人: ***@***.*** ***@***.***> 代表 zhujiem ***@***.***>
日期: 星期一, 2024年5月20日 09:37
收件人: reczoo/FuxiCTR ***@***.***>
抄送: xuened ***@***.***>, Author ***@***.***>
主题: Re: [reczoo/FuxiCTR] 生成的数据格式疑问？ (Issue #91)

麻烦npz格式先使用v2.2.3版本，当前版本可能确实还没适配好。

―

**Comment by zhujiem** [comment]
多分类可以改，修改一下loss和get_label，然后在metrics里改一下就行。

**Comment by xuened** [comment]
***@***.***
感谢感谢，loss和task我在这修改了，get_label我还不知道在哪？
十分感谢您的解答，方便加您一下微信吗，我的微信号是 15934897165

发件人: ***@***.*** ***@***.***> 代表 zhujiem ***@***.***>
日期: 星期一, 2024年5月20日 09:53
收件人: reczoo/FuxiCTR ***@***.***>
抄送: xuened ***@***.***>, Author ***@***.***>
主题: Re: [reczoo/FuxiCTR] 生成的数据格式疑问？ (Issue #91)

多分类可以改，修改一下loss和get_label，然后在metrics里改一下就行。

―
