### ISSUE TITLE
feature embedding bug?

### ISSUE THREAD

**Issue by gaberm** [reczoo/FuxiCTR#94]
Hi, 

I think, I found a bug in the feature_embedding.py file in line 94:
`self.embedding_layers[feature] = tf.keras.layers.Dense(feat_emb_dim, user_bias=False)`

According to the tensorflow docs (https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense), there's no argument user_bias but an argument called **use_bias**. I also get the following error message, when I run DeepFM with numeric features: `TypeError: ('Keyword argument not understood:', 'user_bias')`

**Comment by zhujiem** [comment]
Thanks for reporting the issue.
